### PR TITLE
chore: Upgraded to Core 1.0.0

### PR DESCRIPTION
**Pull request by williamhallatt**
Updated projects to ASP.NET Core 1.0.0
Upgraded tooling (to match VS2015 Update 3 and tooling preview 2)
Match latest VS Core WebAPI application solution structure and file content (not exactly, but is pretty much in line with what you get "out of the box" at the moment when creating a new WebAPI solution through VS).

Thanks for the example and the excellent tutorial! :)

### CODE REVIEW

**Comment by nbarbettini** [comment]
Hey thanks for the PR @williamhallatt! I'll review this when I have a chance 👍

**Comment by nbarbettini** [comment]
Whoops, fatfingered the button. Time for more coffee 😄

**Comment by nbarbettini** [comment]
Thanks again @williamhallatt!

**Comment by williamhallatt** [comment]
@nbarbettini You are most welcome :)  Have a good weekend!

**Pull request merged**
